### ISSUE TITLE
Seems like 1fbf8684c511a0999bbe2fba3ffa61fa200867d1 broke Lezer Playground

### ISSUE THREAD

**Issue by astashov** [sharat87/littletools#1]
Now when you change the grammar, and make errors there, it won't highlight them, it'll always show "Parser okay."

**Comment by sharat87** [comment]
Hey @astashov, thank you so much for reporting this. Should be fixed now, I'm working on deploying it.

**Comment by astashov** [comment]
Woohoo, thank you so much for a quick fix! I use the Lezer Playground A LOT there, it's so convenient!

**Comment by sharat87** [comment]
Haha, thanks! I didn't know folks were using any tool here, let alone the (very bare-bones) Lezer playground. Glad to see it helping others as well. 🙏
